version: 2.1
orbs:
  eventuate-gradle-build-and-test: "eventuate_io/eventuate-gradle-build-and-test@0.2.9"
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-mysql
          script: ./build-and-test-all-mysql.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-mssql
          script: ./build-and-test-all-mssql.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: build-and-test-postgres
          script: ./build-and-test-all-postgres.sh
      - eventuate-gradle-build-and-test/build-and-test:
          name: deploy-artifacts
          context:
            - publish
          requires:
            - build-and-test-mysql
            - build-and-test-mssql
            - build-and-test-postgres
          script: ./deploy-artifacts.sh
